### ISSUE TITLE
Use cloudflare for libs

### ISSUE THREAD

**Issue by WOLFI3654** [WOLFI3654/JavaSciptThings#1]
Remove the contents of the libs folder by using cloudflare

**Comment by hannesfant** [comment]
Is there a reason to why you've used pt v0.5.7 and 0.5.16 instead of the latest versions?

**Comment by WOLFI3654** [comment]
@hannesfant the repository is a few month old. Thats why I want to use cloudflare instead of local files.
It makes updating easier. So it should be no problem to use the lastest version
